// Downloads the site's web fonts for self-hosting (privacy claim: no
// third-party requests). Preserves the CDNs' unicode-range slicing so CJK
// visitors still download only the slices their page uses.
// Usage: node scripts/fetch-fonts.mjs   (rerun to refresh; output is committed)
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const outDir = resolve(root, 'public/fonts');
const filesDir = resolve(outDir, 'files');
mkdirSync(filesDir, { recursive: true });

// Chrome UA so Google serves woff2 + unicode-range CSS.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const SOURCES = [
  'https://fonts.googleapis.com/css2?family=Gowun+Batang:wght@400;700&family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@500;600;700&display=swap',
  'https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css',
];

const fetchText = async (url) => {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
};

let css = '/* generated by scripts/fetch-fonts.mjs — do not edit by hand */\n';
const downloads = new Map(); // absolute url → local basename

for (const source of SOURCES) {
  let text = await fetchText(source);
  // Drop non-woff2 fallback sources (every target browser supports woff2).
  text = text.replace(/url\(([^)]+)\)\s*format\((['"])(?!woff2)[^'"]+\2\)\s*,?/g, '');
  text = text.replace(/,\s*;/g, ';');
  // Collect + rewrite every url() to a local file.
  text = text.replace(/url\((['"]?)([^'")]+)\1\)/g, (_, _q, url) => {
    const abs = new URL(url, source).href;
    let name = abs.split('/').pop().split('?')[0];
    if (!downloads.has(abs)) {
      // Guard against basename collisions across CDNs.
      if ([...downloads.values()].includes(name)) name = `${downloads.size}-${name}`;
      downloads.set(abs, name);
    }
    return `url(./files/${downloads.get(abs)})`;
  });
  css += `\n/* ── ${source} ── */\n${text}\n`;
}

// Download with a small concurrency pool.
const entries = [...downloads.entries()];
console.log(`fetching ${entries.length} font files…`);
let done = 0, bytes = 0;
const pool = 12;
await Promise.all(Array.from({ length: pool }, async () => {
  while (entries.length) {
    const [url, name] = entries.pop();
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${res.status} ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());
    writeFileSync(resolve(filesDir, name), buf);
    bytes += buf.length; done++;
    if (done % 100 === 0) console.log(`  ${done} files…`);
  }
}));

writeFileSync(resolve(outDir, 'fonts.css'), css);
console.log(`done: ${done} files, ${(bytes / 1024 / 1024).toFixed(1)} MB → public/fonts/`);
